# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://stake.roomit.xyz
title: RoomIT
email: admin@roomit.xyz
author: Dwi
description: "Reliable, Secure and Uptime | Nodes Of Validator"
copyright: 'Copyright &copy; 2022 Admin. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
environment: production

# Build settings
markdown: kramdown
permalink: pretty


plugins:
  - jekyll-minifier
jekyll-minifier:
  exclud: '**.*'

collections:
  mainnet:
    output: true
  testnet:
    output: true
  archieve:
    output: true


