# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://stake.roomit.xyz
title: RoomIT
email: admin@roomit.xyz
author: Dwi
description: "Reliable, Secure and Uptime | Nodes Of Validator"
copyright: 'Copyright &copy; 2022 Admin. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty



